FROM mcr.microsoft.com/devcontainers/ruby:3-bullseye

USER $USERNAME
RUN gem update --system && gem install solargraph rails foreman
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R 1000:1000 /commandhistory \
    && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"
