version: 2
updates:
  # GitHub Actionsの依存関係を維持する
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Ruby/Bundlerの依存関係を維持する
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      # メジャーアップデートは自動更新しない
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Dockerの依存関係を維持する
  - package-ecosystem: "docker"
    directory: "/docker/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"

  # Dev Containersの依存関係を維持する
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "devcontainers"
    commit-message:
      prefix: "build"
      include: "scope" 