version: '3'

services:
  app:
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - rails_bundle:/app/vendor/bundle:delegated
      - bashhistory:/commandhistory:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/app_development
      DATABASE_HOST: db
    command: ["sh", "docker/app/startup.sh"]
    tty: true
    stdin_open: true

  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  rails_bundle:
  postgres_volume:
  bashhistory:
