version: '3'

services:
  app:
    container_name: rails-app
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - rails_bundle:/app/vendor/bundle:delegated
      - bashhistory:/commandhistory:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/myapp_development
    command: ["docker/app/startup.sh"]
    tty: true
    stdin_open: true

  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  rails_bundle:
  postgres_volume:
  bashhistory:
