version: '3'

services:
  app:
    image: rails-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ./:/app
    tmpfs:
      - /app/tmp/pids
    ports:
      - 3000:3000
    working_dir: /app
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/myapp_development
    command: ["docker/app/startup.sh"]

  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  postgres_volume:
